{{- $values := $.Values.reth }}
{{- $componentName := "reth" }}
{{- $componentLabel := include "reth.componentLabelFor" $componentName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reth.fullname" . }}-{{ $componentName }}-headless
  labels:
    {{- include "reth.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range $portName, $portNumber := $values.service.ports }}
    - port: {{ $portNumber }}
      targetPort: {{ $portName }}
      protocol: TCP
      name: {{ $portName }}
    {{- end }}
  selector:
    {{- include "reth.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if $values.service.topologyAwareRouting.enabled }}
  annotations:
    {{- if semverCompare ">= 1.27-0" .Capabilities.KubeVersion.GitVersion }}
    service.kubernetes.io/topology-mode: "auto"
    {{- else }}
    service.kubernetes.io/topology-aware-hints: "auto"
    {{- end }}
  {{- end }}
  name: {{ include "reth.fullname" . }}-{{ $componentName }}
  labels:
    {{- include "reth.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
    serviceMonitorTarget: "true"
spec:
  type: {{ $values.service.type }}
  ports:
    {{- range $portName, $portNumber := $values.service.ports }}
    - port: {{ $portNumber }}
      targetPort: {{ $portName }}
      protocol: TCP
      name: {{ $portName }}
    {{- end }}
  selector:
    {{- include "reth.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
{{- if and $.Values.consensus.enabled $.Values.consensus.service.enabled (or $.Values.consensus.beaconApi.enabled $.Values.consensus.metrics.enabled) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reth.fullname" . }}-consensus
  labels:
    {{- include "reth.labels" . | nindent 4 }}
    app.kubernetes.io/component: consensus
spec:
  type: {{ $.Values.consensus.service.type }}
  ports:
    {{- if $.Values.consensus.beaconApi.enabled }}
    - port: {{ $.Values.consensus.beaconApi.port }}
      targetPort: consensus-beacon
      protocol: TCP
      name: beacon-api
    {{- end }}
    {{- if $.Values.consensus.metrics.enabled }}
    - port: {{ $.Values.consensus.metrics.port }}
      targetPort: consensus-metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "reth.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
{{- end }}
{{- if $values.p2pNodePort.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reth.fullname" . }}-{{ $componentName }}-p2p-0
  labels:
    {{- include "reth.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
    pod: {{ include "reth.fullname" . }}-{{ $componentName }}-0
    type: p2p
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: tcp-p2p
      port: {{ include "reth.p2pPort" $values }}
      protocol: TCP
      targetPort: tcp-p2p
      nodePort: {{ $values.p2pNodePort.port }}
    - name: udp-p2p
      port: {{ include "reth.p2pPort" $values }}
      protocol: UDP
      targetPort: udp-p2p
      nodePort: {{ $values.p2pNodePort.port }}
  selector:
    {{- include "reth.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: "{{ include "reth.fullname" $ }}-{{ $componentName }}-0"
{{- end }}
